version: "3"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    expose:
      - "5432"
    env_file: 
      - .env
    networks:
      - back_bdd
      - adminer_bdd

  backend:
    image: backend
    container_name: backend
    build: ./backend
    ports:
      - "7001:5000"
      - "5001:5001"
    env_file: 
      - .env
      
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/root/backend/src:rw
    networks:
      - back_bdd

  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/root/frontend/src:rw
      - ./frontend/public:/root/frontend/public:rw
    env_file: 
      - .env

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - adminer_bdd


networks:
  back_bdd:
    driver: "bridge"
  adminer_bdd:
    driver: "bridge"
